### ISSUE TITLE
Algorithm for earning points and badges

### ISSUE THREAD

**Issue by alexandraciurescu** [unibuc-cs/software-engineering-product-cache-me-if-you-can#7]

**Comment by Alexandra06T** [comment]
- [ ] Create Badge entity
- [ ] Create Action Entity
- [ ] CRUD on badges (admins and moderators can add their own badges and manage them)
- [ ] Implement an automatic way of receiving badges
- [ ] Let admins update the value in reputation point of the possible actions
- [ ] Implement an automatic way of receiving reputation points
